# Generated by Django 3.1 on 2020-11-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Enter username (max 15)', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username (max 15)', max_length=15)),
                ('email', models.EmailField(help_text='Enter you email', max_length=25)),
                ('password', models.CharField(help_text='Enter password (max 20)', max_length=20)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reg_date', 'username'],
            },
        ),
    ]
