# Generated by Django 3.1 on 2020-11-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
